# Generated by Django 6.1 on 2026-08-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, to='autenticacion.tienda')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='EntradaMercancia',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, to='autenticacion.tienda')),
            ],
            options={
                'db_table': 'entradas_mercancia',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('sinonimos', models.JSONField(blank=True, default=list)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
                ('id_tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, to='autenticacion.tienda')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='EntradaItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_entrada', models.ForeignKey(db_column='id_entrada', on_delete=django.db.models.deletion.CASCADE, to='inventario.entradamercancia')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'db_table': 'entrada_items',
            },
        ),
    ]
